spring:
  datasource:
    # (if you’re truly using an embedded H2 for dev; otherwise point these at your real DB)
    url: jdbc:h2:mem:frogcrew;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    # This property changed names in 2.4+: it tells Spring “always run my scripts”
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update    # creates tables if they’re missing
      # (if you have your own schema.sql; otherwise omit)
      schema-locations:
        - classpath:schema.sql

      # this is your insert file:
      data-locations:
        - classpath:data.sql

logging:
  level:
    # Turn on the ScriptUtils so you can see exactly when it’s running your .sql
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
    # Also show the raw SQL from Hibernate (optional)
    org.hibernate.SQL: DEBUG
