spring:
  datasource:
    url: jdbc:h2:file:./frogcrewdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: false 

  jpa:
    defer-datasource-initialization: true  
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console
